on:
  schedule:
    - cron: 3 6 * * 5
  workflow_dispatch:


name: Test APIs

jobs:
  test-apis:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TAN_SWID: ${{ secrets.TAN_SWID }}
      TAN_ESPN_S2: ${{ secrets.TAN_ESPN_S2 }}
      MOCK_BYPASS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::rcmdcheck

      - name: Run Tests
        run: |
          print(Sys.getenv("MOCK_BYPASS"))
          testthat::test_local()
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
